=== alooonsogm/EjerciciosDTDyXML/EjerciciosFinalesDTD/public_html/Centros.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT centros (ies)+>
<!ELEMENT ies (nombre,localidad,cp?,estudios)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT estudios (cicloFormativo)+>
<!ELEMENT cicloFormativo  (alumno|alumna)+>

<!ELEMENT alumno (nombeAlumno,apellido,nota?)>
<!ELEMENT alumna (nombeAlumno,apellido,nota?)>
<!ELEMENT nombeAlumno (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nota (#PCDATA)>


<!ATTLIST ies id ID #REQUIRED>
<!ATTLIST cicloFormativo id ID #IMPLIED>
<!ATTLIST alumno num ID #REQUIRED>
<!ATTLIST alumna num ID #REQUIRED>

=== alooonsogm/EjerciciosDTDyXML/EjerciciosFinalesDTD/public_html/Centros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE centros SYSTEM "centros.dtd">
<centros>
    <ies id="ies_001">
        <nombre>Domenico Scarlatti</nombre>
        <localidad>Aranjuez</localidad>
        <cp>28003</cp>
        <estudios>
            <cicloFormativo id="DAW">  
                <alumno num="n_001">    
                    <nombeAlumno>Robin</nombeAlumno>
                    <apellido>Jáquez</apellido>
                    <nota>10</nota>
                </alumno>
            </cicloFormativo>
            <cicloFormativo>  
                <alumno num="n_002">  
                    <nombeAlumno>Paco</nombeAlumno>
                    <apellido>García</apellido>
                </alumno>
            </cicloFormativo>
        </estudios>  
    </ies>
   
    <ies id="ies_002">
        <nombre>lope de vega</nombre>
        <localidad>Madrid</localidad>
        <estudios>
            <cicloFormativo>  
                <alumno num="n_003">  
                    <nombeAlumno>Pedro</nombeAlumno>
                    <apellido>Perez</apellido>
                    <nota>10</nota>
                </alumno>
            </cicloFormativo>
            <cicloFormativo id="cocina">  
                <alumna num="n_004">   
                    <nombeAlumno>maria</nombeAlumno>
                    <apellido>Perez</apellido>
                </alumna>
                <alumna num="n_005">   
                    <nombeAlumno>daniela</nombeAlumno>
                    <apellido>garcia</apellido>
                    <nota>6.5</nota>
                </alumna>
            </cicloFormativo>
        </estudios>  
    </ies>
</centros>
